USE Service_Station
CREATE TABLE `service_stations` (
  `ss_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL COMMENT 'Service Station Name',
  `address` varchar(255) NOT NULL COMMENT 'Service Station Address',
  `contact_ph` varchar(15) NOT NULL COMMENT 'Service Station Contact Number',
  `mobile` varchar(15) NOT NULL COMMENT 'Service Station Mobile Number',
  `email` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL COMMENT 'Brief description used for comparision',
  `website` varchar(50) DEFAULT NULL,
  `logo_path` varchar(100) DEFAULT NULL,
  `area_id` varchar(10) NOT NULL,
  `brand_id` varchar(3) NOT NULL,
  `weekly_off_id` char(1) NOT NULL DEFAULT '0',
  `timing` varchar(12) NOT NULL COMMENT 'Open and close time',
  `about_workshop` text,
  `about_team` text,
  `facilities` text COMMENT 'Facilities & Services of Service Station ',
  `ss_type_id` varchar(1) NOT NULL COMMENT 'Authorized, specialized, all',
  `pick_drop_km` varchar(2) DEFAULT '0',
  `latitude` float,
  `longitude` float,
  `register_time` timestamp,
  `verify_time` timestamp,
  `approve_time` timestamp,
  `updatedAt` timestamp,
  `createdAt` timestamp,
  PRIMARY KEY (`ss_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1;
