CREATE TABLE `wp_service_stations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL COMMENT 'Service Station Name',
  `address` varchar(100) NOT NULL COMMENT 'Service Station Address',
  `contact` varchar(30) NOT NULL COMMENT 'Service Station Contact Number',
  `email` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `siteaddress` varchar(255) DEFAULT NULL,
  `logopath` varchar(255) DEFAULT NULL,
  `ssarea` varchar(30) NOT NULL,
  `ssbrand` varchar(100) NOT NULL,
  `weeklyoff` varchar(20) NOT NULL,
  `timing` varchar(12) NOT NULL,
  `ownername` varchar(20) NOT NULL,
  `owneremail` varchar(50) NOT NULL,
  `ownermobile` varchar(10) NOT NULL,
  `aboutowner` text,
  `aboutworkshop` text,
  `aboutteam` text,
  `services` text,
  `features` text,
  `lat` float DEFAULT NULL,
  `lang` float DEFAULT NULL,
  `pincode` int(6) NOT NULL,
  `sstype` varchar(20) NOT NULL,
  `pickdropkm` varchar(50) DEFAULT NULL,
  `facilities` text COMMENT 'Facilities & Services of Service Station ',
  `requesttime` datetime NOT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT '0',
  `is_approved` tinyint(4) NOT NULL DEFAULT '0',
  `holidays` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1 AUTO_INCREMENT=9 ;
